### PR TITLE
Make non-govuk headers and footers

### PR DESCRIPTION
**Pull request by maxf**

### CODE REVIEW

**Comment by davidread** [comment]
Have you ascertained that this is definitely the rule? Because if it is then many sites are breaking it, such as:
- https://standards.data.gov.uk/
- https://www.blog.gov.uk/
- https://www.vehicleenquiry.service.gov.uk/
- https://courttribunalfinder.service.gov.uk/
- https://www.civilservicejobs.service.gov.uk/

To try and understand, I'm looking for examples of recent sites that are clearly GDS influenced by avoid the font & header:
- https://publicappointments.cabinetoffice.gov.uk/

**Comment by davidread** [comment]
On the other hand, maybe it's good that data.gov.uk has a separate identity to GOV.UK...

**Comment by maxf** [comment]
https://www.gov.uk/service-manual/user-centred-design/resources/header-footer.html
is pretty clear

**Comment by davidread** [comment]
Ha, good find. I'm sure there is a logic to that...

But I'm cool with being separate.

**Comment by maxf** [comment]
Yeah, I'm in two minds about it, but if we decide we want to be GOV.UK I think we should definitely challenge what's in the service manual

**Pull request merged**
